using System.Collections.Generic;

#nullable enable

namespace ManaMagic.Core.Metadata
{
    /// <summary>
    /// Static class containing metadata for various data within the Secret of Mana ROM file.
    /// </summary>
    public static partial class ManaMetadata
    {
        private static readonly IReadOnlyDictionary<byte, string> SpriteNameStrings = new Dictionary<byte, string>()
        {
            { 0x00, "Rabite" },
            { 0x01, "Buzz Bee" },
            { 0x02, "Mushboom" },
            { 0x03, "Chobin Hood" },
            { 0x04, "Lullabud" },
            { 0x05, "Iffish" },
            { 0x06, "Kid Goblin" },
            { 0x07, "Eye Spy" },
            { 0x08, "Green Drop" },
            { 0x09, "Specter" },
            { 0x0A, "Blat" },
            { 0x0B, "Goblin" },
            { 0x0C, "Water Thug" },
            { 0x0D, "Polter Chair" },
            { 0x0E, "Ma Goblin" },
            { 0x0F, "Dark Funk" },
            { 0x10, "Crawler" },
            { 0x11, "Ice Thug" },
            { 0x12, "Zombie" },
            { 0x13, "Kimono Bird" },
            { 0x14, "Silktail" },
            { 0x15, "Nemesis Owl" },
            { 0x16, "Pebbler" },
            { 0x17, "Pumpkin Bomb" },
            { 0x18, "Steamed Crab" },
            { 0x19, "Chess Knight" },
            { 0x1A, "Wizard Eye" },
            { 0x1B, "Howler" },
            { 0x1C, "Robin Foot" },
            { 0x1D, "LA Funk" },
            { 0x1E, "Grave Bat" },
            { 0x1F, "Werewolf" },
            { 0x20, "Shadow X3" },
            { 0x21, "Evil Sword" },
            { 0x22, "Tomato Man" },
            { 0x23, "Mystic Book" },
            { 0x24, "Sand Stinger" },
            { 0x25, "Mad Mallard" },
            { 0x26, "Emberman" },
            { 0x27, "Red Drop" },
            { 0x28, "Eggatrice" },
            { 0x29, "Bomb Bee" },
            { 0x2A, "Mushgloom" },
            { 0x2B, "Trap Flower" },
            { 0x2C, "Dinofish" },
            { 0x2D, "Mimic Box" },
            { 0x2E, "Shadow X1" },
            { 0x2F, "Kimono Wizard" },
            { 0x30, "Ghost" },
            { 0x31, "Metal Crawler" },
            { 0x32, "Spider Legs" },
            { 0x33, "Weepy Eye" },
            { 0x34, "Shellblast" },
            { 0x35, "Beast Zombie" },
            { 0x36, "Ghoul" },
            { 0x37, "Imp" },
            { 0x38, "Blue Drop" },
            { 0x39, "Marmablue" },
            { 0x3A, "Fierce Head" },
            { 0x3B, "Griffin Hand" },
            { 0x3C, "Needlion" },
            { 0x3D, "Metal Crab" },
            { 0x3E, "Armored Man" },
            { 0x3F, "Shadow X2" },
            { 0x40, "Eggplant Man" },
            { 0x41, "Captain Duck" },
            { 0x42, "Nitro Pumpkin" },
            { 0x43, "Turtlance" },
            { 0x44, "Tsunami" },
            { 0x45, "Basilisk" },
            { 0x46, "Gremlin" },
            { 0x47, "Steelpion" },
            { 0x48, "Dark Ninja" },
            { 0x49, "Whimper" },
            { 0x4A, "Heck Hound" },
            { 0x4B, "Fiend Head" },
            { 0x4C, "National Scar" },
            { 0x4D, "Dark Stalker" },
            { 0x4E, "Dark Knight" },
            { 0x4F, "Shape Shifter" },
            { 0x50, "Wolf Lord" },
            { 0x51, "Doom Sword" },
            { 0x52, "Terminator" },
            { 0x53, "Master Ninja" },
            { 0x54, "?" },
            { 0x55, "Crystal Orb" },
            { 0x56, "Treasure Chest Control" },
            { 0x57, "Mantis Ant" },
            { 0x58, "Wall Face" },
            { 0x59, "Tropicallo" },
            { 0x5A, "Minotaur" },
            { 0x5B, "Spikey Tiger" },
            { 0x5C, "Jabberwocky" },
            { 0x5D, "Spring Beak" },
            { 0x5E, "Frost Gigas" },
            { 0x5F, "Snap Dragon" },
            { 0x60, "Mech Rider I" },
            { 0x61, "Doom's Wall" },
            { 0x62, "Vampire" },
            { 0x63, "Metal Mantis" },
            { 0x64, "Mech Rider II" },
            { 0x65, "Kilroy" },
            { 0x66, "Gorgon Bull" },
            { 0x67, "Brambler" },
            { 0x68, "Boreal Face" },
            { 0x69, "Great Viper" },
            { 0x6A, "Lime Slime" },
            { 0x6B, "Blue Spike" },
            { 0x6C, "Chamber's Eye" },
            { 0x6D, "Hydra" },
            { 0x6E, "Aegagropilon" },
            { 0x6F, "Hexas" },
            { 0x70, "Kettle Kin" },
            { 0x71, "Tonpole" },
            { 0x72, "Mech Rider III" },
            { 0x73, "Snow Dragon" },
            { 0x74, "Fire Gigas" },
            { 0x75, "Red Dragon" },
            { 0x76, "Axe Beak" },
            { 0x77, "Blue Dragon" },
            { 0x78, "Buffy" },
            { 0x79, "Dark Lich" },
            { 0x7A, "Biting Lizard" },
            { 0x7B, "Dragon Worm" },
            { 0x7C, "Dread Slime" },
            { 0x7D, "Thunder Gigas" },
            { 0x7E, "Doom's Eye" },
            { 0x7F, "Mana Beast" },
            { 0x80, "Randi" },
            { 0x81, "Purim" },
            { 0x82, "Popoie" },
            { 0x83, "Monster Snowman" },
            { 0x84, "Red Spell Palette Placeholder" },
            { 0x85, "Blue Spell Palette Placeholder" },
            { 0x86, "Green Spell Palette Placeholder" },
            { 0x87, "Yellow Spell Palette Placeholder" },
            { 0x88, "Midget Moogle/Purple Spell Palette Placeholder" },
            { 0x89, "Salamando's Stove" },
            { 0x8A, "Randi (Cutscene Version)" },
            { 0x8B, "Purim (Cutscene Version)" },
            { 0x8C, "Popoie (Cutscene Version)" },
            { 0x8D, "Weapon Recharge Palette Placeholder" },
            { 0x8E, "White Spell Palette Placeholder" },
            { 0x8F, "Black Spell Palette Placeholder" },
            { 0x90, "Gnome" },
            { 0x91, "Undine" },
            { 0x92, "Salamando" },
            { 0x93, "Sylphid" },
            { 0x94, "Lumina" },
            { 0x95, "Shade" },
            { 0x96, "Luna" },
            { 0x97, "Dryad" },
            { 0x98, "Moogle" },
            { 0x99, "Neko" },
            { 0x9A, "Dwarf" },
            { 0x9B, "Dwarven Chief" },
            { 0x9C, "Watts" },
            { 0x9D, "Sprite Grandpa" },
            { 0x9E, "King Truffle" },
            { 0x9F, "Walrus Villager" },
            { 0xA0, "Jema" },
            { 0xA1, "Luka" },
            { 0xA2, "Fake Sage Joch" },
            { 0xA3, "Sage Joch" },
            { 0xA4, "Scorpion Boss" },
            { 0xA5, "Scorpion Henchman" },
            { 0xA6, "Phanna" },
            { 0xA7, "Krissie" },
            { 0xA8, "Sergo" },
            { 0xA9, "Cultist" },
            { 0xAA, "Temple Monk" },
            { 0xAB, "Pecard" },
            { 0xAC, "Dyluck" },
            { 0xAD, "Rudolph" },
            { 0xAE, "Santa" },
            { 0xAF, "Mushroom Villager" },
            { 0xB0, "Emperor Vandole" },
            { 0xB1, "Geshtar" },
            { 0xB2, "Fanha" },
            { 0xB3, "Lost Lacky" },
            { 0xB4, "Sheex" },
            { 0xB5, "Flammie Head" },
            { 0xB6, "Imperial Soldier" },
            { 0xB7, "Republic Soldier" },
            { 0xB8, "General Meria" },
            { 0xB9, "Admiral Morie" },
            { 0xBA, "Elinee" },
            { 0xBB, "Old Man Villager" },
            { 0xBC, "Female Villager (Green Hair)" },
            { 0xBD, "King" },
            { 0xBE, "Mana Fortress Cannon" },
            { 0xBF, "Thanatos" },
            { 0xC0, "Elliot" },
            { 0xC1, "Timothy" },
            { 0xC2, "Resistance Man" },
            { 0xC3, "Resistance Woman" },
            { 0xC4, "Potos Guard" },
            { 0xC5, "Pink Dress Villager" },
            { 0xC6, "Long Hair & Dress Villager" },
            { 0xC7, "Child Hat Villager" },
            { 0xC8, "Female Child Villager" },
            { 0xC9, "Village Elder (Green Robe)" },
            { 0xCA, "Old Woman" },
            { 0xCB, "Mara" },
            { 0xCC, "Mini-Mana Beast" },
            { 0xCD, "Flammie Body" },
            { 0xCE, "Cannon Travel Man" },
            { 0xCF, "Shop Owner" },
            { 0xD0, "Glitched Salamando Stove (Dummied Out)" },
            { 0xD1, "Long Hair & Dress Villager (Strange Palette)" },
            { 0xD2, "Veedio" },
            { 0xD3, "High Stepper" },
            { 0xD4, "Cannon Fuse" },
            { 0xD5, "Cannon Explosion 01" },
            { 0xD6, "Cannon Explosion 02" },
            { 0xD7, "Serin" },
            { 0xD8, "Mana Sword In Stone" },
            { 0xD9, "Cannon Barrel Tip" },
            { 0xDA, "Cannon Barrel" },
            { 0xDB, "Waterfall//Geyser Effect" },
            { 0xDC, "Cannon Lower Left Section" },
            { 0xDD, "Cannon Barrel Section" },
            { 0xDE, "Cannon Lower Right Section" },
            { 0xDF, "Mana Seed" },
            { 0xE0, "Pygmy Randi (Broken Palette)" },
            { 0xE1, "Pygmy Purim (Broken Palette)" },
            { 0xE2, "Pygmy Popoie (Broken Palette)" },
            { 0xE3, "Female Villager (Palette Only?)" },
            { 0xE4, "Ghost Randi" },
            { 0xE5, "Ghost Purim" },
            { 0xE6, "Ghost Popoie" },
            { 0xE7, "Female Villager (Palette Only?)" },
            { 0xE8, "Female Villager (Palette Only?)" },
            { 0xE9, "Female Villager (Palette Only?)" },
            { 0xEA, "Treasure Chest (Dropped)" },
            { 0xEB, "Treasure Chest (Static)" },
            { 0xEC, "Statue" },
            { 0xED, "Pygmy Statue" },
            { 0xEE, "Snowman" },
            { 0xEF, "Pygmy Snowman" },
            { 0xF0, "Randi Moogle" },
            { 0xF1, "Purim Moogle" },
            { 0xF2, "Popoie Moogle" },
            { 0xF3, "Randi Pygmy Moogle" },
            { 0xF4, "Purim Pygmy Moogle" },
            { 0xF5, "Popoie Pygmy Moogle" },
            { 0xF6, "Pygmy Randi" },
            { 0xF7, "Pygmy Purim" },
            { 0xF8, "Pygmy Popoie" },
            { 0xF9, "Death Sprite: Splat" },
            { 0xFA, "Death Sprite: Feathers" },
            { 0xFB, "Death Sprite: Ghost" },
            { 0xFC, "Death Sprite: Goo" },
            { 0xFD, "Death Sprite: Insect Bones" },
            { 0xFE, "Death Sprite: Explosion" },
            { 0xFF, "Death Sprite: Humanoid Bones" },
        };
    }
}