<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Documentation\BossSpriteSlot.xml" />
    <None Remove="Documentation\RAMLayout.xml" />
    <None Remove="Documentation\SpriteSlot.xml" />
    <None Remove="Help\CutContent.rtf" />
    <None Remove="Help\SpecialValues.rtf" />
    <None Remove="Help\SpriteSlotMemoryMap.rtf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Documentation\BossSpriteSlot.xml" />
    <EmbeddedResource Include="Documentation\RAMLayout.xml" />
    <EmbeddedResource Include="Documentation\SpriteSlot.xml" />
    <EmbeddedResource Include="Help\CutContent.rtf" />
    <EmbeddedResource Include="Help\SpecialValues.rtf" />
    <EmbeddedResource Include="Help\SpriteSlotMemoryMap.rtf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="5.0.0" />
  </ItemGroup>

</Project>
