#nullable enable

namespace ManaMagic.Core
{
    public enum ManaSpell : byte
    {
        EarthSlide = 0x00,
        GemMissile = 0x01,
        SpeedDown = 0x02,
        StoneSaber = 0x03,
        SpeedUp = 0x04,
        Defender = 0x05,
        Freeze = 0x06,
        AcidStorm = 0x07,
        EnergyAbsorb = 0x08,
        IceSaber = 0x09,
        Remedy = 0x0A,
        CureWater = 0x0B,
        Fireball = 0x0C,
        Exploder = 0x0D,
        LavaWave = 0x0E,
        FlameSaber = 0x0F,
        FireBouquet = 0x10,
        BlazeWall = 0x11,
        AirBlast = 0x12,
        Thunderbolt = 0x13,
        Silence = 0x14,
        ThunderSaber = 0x15,
        Balloon = 0x16,
        Analyzer = 0x17,
        ChangeForm = 0x18,
        MPAbsorb = 0x19,
        LunarMagic = 0x1A,
        MoonSaber = 0x1B,
        LunarBoost = 0x1C,
        MoonEnergy = 0x1D,
        SleepFlower = 0x1E,
        Burst = 0x1F,
        ManaMagicPopoie = 0x20,
        Revivifer = 0x21,
        Wall = 0x22,
        ManaMagicPurim = 0x23,
        EvilGate = 0x24,
        DarkForce = 0x25,
        DispelMagic = 0x26,
        LightSaber = 0x27,
        LucentBeam = 0x28,
        LucidBarrier = 0x29,
    }
}