<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>ManaSword.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Controls\PaletteControl.cs~RF2c8dcdcd.TMP" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ManaMagic.Core\ManaMagic.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\PaletteControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\PaletteLabel.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\UserControls\Boss\BossSkillViewerUserControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>