#nullable enable

namespace ManaMagic.Core.Events
{
    public enum AddItemType : byte
    {
        BareHead = 0x00,
        Bandanna = 0x01,
        HairRibbon = 0x02,
        RabiteCap = 0x03,
        HeadGear = 0x04,
        QuillCap = 0x05,
        SteelCap = 0x06,
        GoldenTiara = 0x07,
        RaccoonCap = 0x08,
        QuiltedHood = 0x09,
        TigerCap = 0x0A,
        Circlet = 0x0B,
        RubyArmet = 0x0C,
        UnicornHelm = 0x0D,
        DragonHelm = 0x0E,
        DuckHelm = 0x0F,
        NeedleHelm = 0x10,
        CockatriceCap = 0x11,
        AmuletHelm = 0x12,
        GriffinHelm = 0x13,
        FaerieCrown = 0x14,

        No = 0x15,
        Overalls = 0x16,
        KungFuSuit = 0x17,
        MidgeRobe = 0x18,
        ChainVest = 0x19,
        SpikySuit = 0x1A,
        KungFuDress = 0x1B,
        FancyOveralls = 0x1C,
        ChestGuard = 0x1D,
        GoldenVest = 0x1E,
        RubyVest = 0x1F,
        TigerSuit = 0x20,
        TigerBikini = 0x21,
        MagicalArmor = 0x22,
        TortoiseMail = 0x23,
        FlowerSuit = 0x24,
        BattleSuit = 0x25,
        Vestguard = 0x26,
        VampireCape = 0x27,
        PowerSuit = 0x28,
        FaerieCloak = 0x29,

        Nothing = 0x2A,
        FaeriesRing = 0x2B,
        ElbowPad = 0x2C,
        PowerWrist = 0x2D,
        CobraBracelet = 0x2E,
        WolfsBand = 0x2F,
        SilverBand = 0x30,
        GolemRing = 0x31,
        FrostyRing = 0x32,
        IvyAmulet = 0x33,
        GoldBracelet = 0x34,
        ShieldRing = 0x35,
        LazuriRing = 0x36,
        GuardianRing = 0x37,
        Gauntlet = 0x38,
        NinjaGloves = 0x39,
        DragonRing = 0x3A,
        WatcherRing = 0x3B,
        ImpsRing = 0x3C,
        AmuletRing = 0x3D,
        Wristband = 0x3E,
        DummiedItem = 0x3F,

        Candy = 0x40,
        Chocolate = 0x41,
        RoyalJam = 0x42,
        FaerieWalnut = 0x43,
        MedicalHerb = 0x44,
        CupOfWishes = 0x45,
        MagicRope = 0x46,
        FlammieDrum = 0x47,
        MoogleBelt = 0x48,
        MidgeMallet = 0x49,
        Barrel = 0x4A,
        QuestionMark = 0x4B,

        SpikeKnuckle = 0x80,
        PowerGlove = 0x81,
        MoogleClaws = 0x82,
        ChakraHand = 0x83,
        HeavyGlove = 0x84,
        HyperFist = 0x85,
        GriffinClaws = 0x86,
        DragonClaws = 0x87,
        AuraGlove = 0x88,

        RustySword = 0x89,
        BroadSword = 0x8A,
        HeraldSword = 0x8B,
        Claymore = 0x8C,
        Excalibur = 0x8D,
        Masamune = 0x8E,
        GigasSword = 0x8F,
        DragonBuster = 0x90,
        ManaSword = 0x91,

        WattsAxe = 0x92,
        LodeAxe = 0x93,
        StoutAxe = 0x94,
        BattleAxe = 0x95,
        GoldenAxe = 0x96,
        WereBuster = 0x97,
        GreatAxe = 0x98,
        GigasAxe = 0x99,
        DoomAxe = 0x9A,

        Spear = 0x9B,
        HeavySpear = 0x9C,
        SpritesSpear = 0x9D,
        Partisan = 0x9E,
        Halberd = 0x9F,
        OceanidSpear = 0xA0,
        GigasLance = 0xA1,
        DragonLance = 0xA2,
        DaedalusLance = 0xA3,

        Whip = 0xA4,
        BlackWhip = 0xA5,
        BackhandWhip = 0xA6,
        ChainWhip = 0xA7,
        FlailofHope = 0xA8,
        MorningStar = 0xA9,
        HammerFlail = 0xAA,
        NimbusChain = 0xAB,
        GigasFlail = 0xAC,

        ChobinsBow = 0xAD,
        ShortBow = 0xAE,
        LongBow = 0xAF,
        GreatBow = 0xB0,
        BowofHope = 0xB1,
        ElfinBow = 0xB2,
        WingBow = 0xB3,
        DoomBow = 0xB4,
        GarudaBuster = 0xB5,

        Boomerang = 0xB6,
        Chakram = 0xB7,
        LodeBoomerang = 0xB8,
        RisingSun = 0xB9,
        RedCleaver = 0xBA,
        CobraShuttle = 0xBB,
        Frizbar = 0xBC,
        Shuriken = 0xBD,
        NinjasTrump = 0xBE,

        PoleDart = 0xBF,
        Javelin = 0xC0,
        LightTrident = 0xC1,
        LodeJavelin = 0xC2,
        ForkofHope = 0xC3,
        ImpsFork = 0xC4,
        ElfsHarpoon = 0xC5,
        DragonDart = 0xC6,
        Valkyrian = 0xC7,
    }
}