#nullable enable

namespace ManaMagic.Core.Items
{
    public enum WeaponClassType : byte
    {
        PlayerGlove = 0x00,
        PlayerSword = 0x01,
        PlayerAxe = 0x02,
        PlayerSpear = 0x03,
        PlayerWhip = 0x04,
        PlayerBow = 0x05,
        PlayerBoomerang = 0x06,
        PlayerJavelin = 0x07,
        PlayerGrimReaper = 0x08,
        PlayerPygmyEngulf = 0x09,
        PlayerEngulf = 0x0A,
        PlayerPygmyBarrel = 0x0B,
        PlayerBarrel = 0x0C,
        PlayerPygmyKick = 0x0D,
        PlayerMoogleBalloon = 0x0E,
        PlayerMidBalloon = 0x0F,

        PlayerLowBalloon = 0x10,
        EnemyEngulf = 0x11,
        EnemyBarrel = 0x12,
        EnemyMoogleBalloon = 0x13,
        EnemyMidBalloon = 0x14,
        EnemyLowBalloon = 0x15,
        UnusedEnemyBoomerang01 = 0x16,
        UnusedEnemyBoomerang02 = 0x17,
        ChobinHood = 0x18,
        Lullabud = 0x19,
        WeepyEye = 0x1A,
        Basilisk = 0x1B,
        Blat = 0x1C,
        Bee = 0x1D,
        Eggatrice = 0x1E,
        UnusedEnemyFireball = 0x1F,

        Duck = 0x20,
        Crab = 0x21,
        FierceHeadMelee = 0x22,
        TomatoMan = 0x23,
        LivingSword = 0x24,
        EyeSpy = 0x25,
        KimonoBird = 0x26,
        Funk = 0x27,
        FishMelee = 0x28,
        Ghost = 0x29,
        GoblinMelee = 0x2A,
        Marmablue = 0x2B,
        GriffinHand = 0x2C,
        LivingDrop = 0x2D,
        Emberman = 0x2E,
        Crawler = 0x2F,

        Book = 0x30,
        Chair = 0x31,
        Mushroom = 0x32,
        MimicBox = 0x33,
        Pebbler = 0x34,
        NinjaMelee = 0x35,
        Owl = 0x36,
        Pumpkin = 0x37,
        Rabite = 0x38,
        Thug = 0x39,
        Stinger = 0x3A,
        SpiderLegs = 0x3B,
        ImpMelee = 0x3C,
        Turtle = 0x3D,
        ChessKnight = 0x3E,
        Werewolf = 0x3F,

        Dog = 0x40,
        Zombie = 0x41,
        ImpRanged = 0x42,
        FierceHeadRanged = 0x43,
        FishRanged = 0x44,
        ArmoredMan = 0x45,
        GoblinRanged = 0x46,
        NinjaRanged = 0x47,
        ShapeShifter = 0x48,
    }
}