#nullable enable

namespace ManaMagic.Core.Items
{
    public enum WeaponType : byte
    {
        SpikeKnuckle = 0x00,
        PowerGlove = 0x01,
        MoogleClaws = 0x02,
        ChakraHand = 0x03,
        HeavyGlove = 0x04,
        HyperFist = 0x05,
        GriffinClaws = 0x06,
        DragonClaws = 0x07,
        AuraGlove = 0x08,

        RustySword = 0x09,
        BroadSword = 0x0A,
        HeraldSword = 0x0B,
        Claymore = 0x0C,
        Excalibur = 0x0D,
        Masamune = 0x0E,
        GigasSword = 0x0F,
        DragonBuster = 0x10,
        ManaSword = 0x11,

        WattsAxe = 0x12,
        LodeAxe = 0x13,
        StoutAxe = 0x14,
        BattleAxe = 0x15,
        GoldenAxe = 0x16,
        WereBuster = 0x17,
        GreatAxe = 0x18,
        GigasAxe = 0x19,
        DoomAxe = 0x1A,

        Spear = 0x1B,
        HeavySpear = 0x1C,
        SpritesSpear = 0x1D,
        Partisan = 0x1E,
        Halberd = 0x1F,
        OceanidSpear = 0x20,
        GigasLance = 0x21,
        DragonLance = 0x22,
        DaedalusLance = 0x23,

        Whip = 0x24,
        BlackWhip = 0x25,
        BackhandWhip = 0x26,
        ChainWhip = 0x27,
        FlailofHope = 0x28,
        MorningStar = 0x29,
        HammerFlail = 0x2A,
        NimbusChain = 0x2B,
        GigasFlail = 0x2C,

        ChobinsBow = 0x2D,
        ShortBow = 0x2E,
        LongBow = 0x2F,
        GreatBow = 0x30,
        BowofHope = 0x31,
        ElfinBow = 0x32,
        WingBow = 0x33,
        DoomBow = 0x34,
        GarudaBuster = 0x35,

        Boomerang = 0x36,
        Chakram = 0x37,
        LodeBoomerang = 0x38,
        RisingSun = 0x39,
        RedCleaver = 0x3A,
        CobraShuttle = 0x3B,
        Frizbar = 0x3C,
        Shuriken = 0x3D,
        NinjasTrump = 0x3E,

        PoleDart = 0x3F,
        Javelin = 0x40,
        LightTrident = 0x41,
        LodeJavelin = 0x42,
        ForkofHope = 0x43,
        ImpsFork = 0x44,
        ElfsHarpoon = 0x45,
        DragonDart = 0x46,
        Valkyrian = 0x47,
    }
}